const arrayMaking = (a, b, n, mod)=>{
    let arr = [];
    arr.push(a);
    arr.push(b);
    for(let i = 2;i<n;i++)
    {
      arr.push((arr[i-1]+arr[i-2])%mod)
    }
  return force(arr,n)
}
// const force = (arr,n)=>{
//   let count = 1
//   let sum =0;  
//   for(let  i =1 ;i<n;i++){
//       if(arr[i]===arr[i-1])
//       {
//         count++;
//       }
//       else
//       {
//         sum += count ** 2
//         count = 1;
//       }
//     }
    
//     return sum + count**2
// }

const force = (arr,n) =>{
    let map = new Map();
    for(let  i = 0 ; i<n;i++)
    {
      if(map.has(arr[i]))
      {
        map.set(arr[i],map.get(arr[i])+1);
      }
      else
      {
        map.set(arr[i],1);
      }
    }
   // console.log(map.values());
    let sum=0;
    map.forEach((val,key)=>{
        sum+=val**2
    })
    return sum;
}
function runProgram(input) {
  // Write code here
input=input.trim().split('\n');
let  t = +input[0]
let l=1;
for(let i =0 ;i<t;i++)
{
    let arr = input[l++].trim().split(" ").map(Number);
    console.log(arrayMaking(arr[0],arr[1],arr[2],arr[3]));
}
}
if (process.env.USERNAME === "Ashish Singh") {
    runProgram(`2
0 1 6 4
1 1 4 2`);
} else {
  process.stdin.resume();
  process.stdin.setEncoding("ascii");
  let read = "";
  process.stdin.on("data", function (input) {
    read += input;
  });
  process.stdin.on("end", function () {
    read = read.replace(/\n$/, "");
    read = read.replace(/\n$/, "");
    runProgram(read);
  });
  process.on("SIGINT", function () {
    read = read.replace(/\n$/, "");
    runProgram(read);
    process.exit(0);
  });
}

// The first line contains integer T denoting the number of test cases.The following T lines contain 4 integers each: A[0], A[1], N, MOD.

// Array A of N elements is generated by the following way:

// A[0], A[1] are given

// A[i] = (A[i - 1] + A[i - 2]) modulo MOD for 1 < i < N.